name: CI
run-name: ${{ github.actor }}
on: push

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test-linux:
    name: test-linux
    strategy:
      fail-fast: false
      matrix:
        image:
          - gcc:13

        build-type:
          - Debug

    runs-on: ubuntu-latest
    container:
      image: ${{matrix.image}}
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: install-ninj-cmake
        run: apt-get update && apt-get install -y ninja-build cmake doctest

      - name: configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

      - name: build
        run: cmake --build build

      - name: run-tests
        run: ./build/tb_scope_exit_test
